[package]
name = "BCIScriptC"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
nom_locate = "4.0.0"
simple-error = "0.2"
lazy_static = "1.4.0"
nom-peg = "0.1.1"
logos = "0.13"
